/*
  Warnings:

  - The values [MINIMUM_PASSWORD_LENGTH,DB_CLEANUP_DAYS] on the enum `Settings` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "public"."Settings_new" AS ENUM ('DAYS_UNTIL_OVERDUE', 'PAYMENT_DUE_DAY', 'OVERDUE_FEE_VALUE', 'OVERDUE_FEE_IS_PERCENTAGE', 'SESSION_TIMEOUT_MINUTES', 'IS_USER_REGISTRATION_ENABLED', 'DB_CLEANUP_DAY', 'SOFT_DELETED_MODELS_TO_PURGE', 'AUDIT_LOG_RETENTION_DAYS', 'CURRENCY_SYMBOL', 'ACTUAL_SCHOOL_YEAR_ID', 'ACTUAL_SCHOOL_PERIOD_ID', 'ACTUAL_SCHOOL_MONTH_ID', 'AUTO_SET_ACTUAL_SCHOOL_PERIOD_MONTH_AND_YEAR', 'SEARCH_THRESHOLD', 'PUBLIC_REGISTRATION_ENABLED', 'PERIOD_ALIAS', 'AUTO_ENROLL_STUDENTS_IN_NEW_PERIOD', 'AUTO_ENROLL_STUDENTS_IN_NEW_GRADE', 'AUTO_ENROLL_PERIOD_CRON_DAY', 'AUTO_ENROLL_GRADE_CRON_DATE');
ALTER TABLE "public"."Setting" ALTER COLUMN "name" TYPE "public"."Settings_new" USING ("name"::text::"public"."Settings_new");
ALTER TYPE "public"."Settings" RENAME TO "Settings_old";
ALTER TYPE "public"."Settings_new" RENAME TO "Settings";
DROP TYPE "public"."Settings_old";
COMMIT;
