import { Request, Response } from "express";
import { TYPES } from "../../config/types";
import { container } from "../../config/container";
import { SchoolYearFeature } from "../../features/schoolYear.feature";
import { CreateSchoolYearSchema } from "./schemas";

export async function createSchoolYear(req: Request, res: Response) {
  const { startDate, endDate, automaticallyGenerateSchoolPeriodsAndMonths } =
    CreateSchoolYearSchema.parse(req.body);

  const schoolYearFeature = container.get<SchoolYearFeature>(
    TYPES.SchoolYearFeature
  );

  const schoolYear = await schoolYearFeature.create(
    new Date(startDate),
    new Date(endDate),
    automaticallyGenerateSchoolPeriodsAndMonths
  );

  res
    .status(201)
    .json({
      schoolYear: schoolYear.schoolYear,
      extraAutoGeneratedData: schoolYear.extraAutoGeneratedData,
    });
}
